 python中使用Skimage进行图像的批量处理 运行程序出错，急需解决，谢谢！
图像批量转换为灰度图，先定义一个函数，然后将这个函数作为第二个参数，运行如下代码，再运行中程序报错，报错内容在代码之后，请问谁能帮忙解决，谢谢！
from skimage import data_dir,io,color
def convert_gray(f):
    rgb=io.imread(f)
    return color.rgb2gray(rgb)
str=data_dir+'/*.png'
coll = io.ImageCollection(str,load_func=convert_gray)
io.imshow(coll[10])
TypeError                                 Traceback (most recent call last) in ()
      7 str=data_dir+'/*.png'
      8 coll = io.ImageCollection(str,load_func=convert_gray)
----> 9 io.imshow(coll[10])
C:\Anaconda2\lib\site-packages\skimage\io\collection.pyc in getitem(self, n)
    258                     if img_num is not None:
    259                         self.data[idx] = self.load_func(fname, img_num=img_num,
--> 260                                                         **kwargs)
    261                     else:
    262                         self.data[idx] = self.load_func(fname, **kwargs)
TypeError: convert_gray() got an unexpected keyword argument 'img_num' 
----------------------------------------------------------------------------------------------------
将def convert_gray(f)改为def convert_gray(f,**args)试试