### 问题描述：
<p>python爬虫 将爬取到的数据导入MongoDB数据库中报错</p>
爬取的数据存储到MongoDB数据库中

```python
import requests                                     #导入库
import json                                         #导入库
url = 'http://www.ptpress.com.cn/bookinfo/getBookListForWS' #设置访问链接
return_data = requests.get(url).text                       #发送访问请求并获得文本信息
data = json.loads(return_data)                             #将数据json化
news = data['data']                                        #索引到data数据

import pymongo  #导入库
MONGO_URL = 'localhost'                  #设置主机IP
client = pymongo.MongoClient(MONGO_URL)  #访问mongo数据库
db = client['pythondb']                  #获取名为pythondb的数据库
collection = db.test                    #获取名为test的集合
for n in news:
    bookName = n['bookName']
    author = n['author']
    price = n['price']
    a = {'bookName':bookName,'author':author,'price':price}
    collection.insert_one(a)             #插入数据
   print(a)


```

已经安装导入了pymongo库 但还是报错了请问怎样解决这些报错内容呢？谢谢 
### 修改方案：


```python

import requests                                     #导入库
import json                                         #导入库
import pymongo  #导入库
url = 'http://www.ptpress.com.cn/bookinfo/getBookListForWS' #设置访问链接
return_data = requests.get(url).text                       #发送访问请求并获得文本信息
data = json.loads(return_data)                             #将数据json化
news = data['data']                                        #索引到data数据

MONGO_URL = '192.168.16.238'                  #设置主机IP
client = pymongo.MongoClient(host=MONGO_URL,port=27017)  #访问mongo数据库
db = client['crm']                  #获取名为pythondb的数据库
collection = db['test']                    #获取名为test的集合

for n in news:
    bookName = n['bookName']
    author = n['author']
    price = n['price']
    a = {'bookName':bookName,'author':author,'price':price}
    collection.insert_one(a)             #插入数据
    print(a)

```


### 人工打分：
